name: Get Images for Build
description: Get Images for Build

inputs:
  image_flavor:
    description: "Types of Image to Build (Bazzite, Desktop, Server)"
    required: true

outputs:
  images:
    description: "List of Images that will be built"
    value: ${{ steps.images.outputs.images }}

runs:
  using: "composite"
  name: Get Images for Build
  steps:
    - name: Get Images for Build
      id: images
      shell: bash
      run: |
        case "${{ inputs.image_flavor }}" in
        "Bazzite")
          images='["bazzite", "bazzite-deck"]'
        ;;
        "Desktop")
          images='["aurora", "aurora-nvidia", "bluefin", "bluefin-nvidia", "cosmic", "cosmic-nvidia"]'
        ;;
        "Server")
          images='["ucore", "ucore-nvidia"]'
        esac
        echo "images=$images" >> "$GITHUB_OUTPUT"
