---
name: Get Images for Build
description: Get Images for Build
inputs:
  image_flavor:
    description: "Types of Image to Build (Bazzite, Desktop, Server)"
    required: true
outputs:
  images:
    description: "List of Images that will be built"
    value: ${{ steps.images.outputs.images }}
runs:
  using: "composite"
  steps:
    - name: Get Images for Build
      id: images
      shell: bash
      run: |-
        # Array to Hold Image Names
        images=()

        # Add Images
        case "${{ inputs.image_flavor }}" in
        "Bazzite")
          images+=("bazzite" "bazzite-deck")
          ;;
        "Desktop")
          # images+=("aurora" "aurora-nvidia")
          images+=("aurora" "aurora-nvidia")
          images+=("bluefin" "bluefin-nvidia")
          images+=("cosmic" "cosmic-nvidia")
          ;;
        "Server")
          images+=("ucore" "ucore-nvidia")
          ;;
        "Beta-Bazzite")
          images+=("bazzite-beta" "bazzite-deck-beta")
          ;;
        "Beta-Desktop")
          # images+=("aurora-beta" "aurora-nvidia-beta")
          images+=("aurora-beta")
          images+=("bluefin-beta" "bluefin-nvidia-beta")
          images+=("cosmic-beta" "cosmic-nvidia-beta")
          ;;
        "Beta-Server")
          images+=("ucore-beta" "ucore-nvidia-beta")
          ;;
        esac

        # Make into Json Array
        images="$(jq --null-input --compact-output '$ARGS.positional' \
        --args "${images[@]}")"

        # Output
        echo "images=$images" >> "$GITHUB_OUTPUT"
