name: Build m2os
on:
  schedule:
    - cron: "41 6 * * 0" # 6:41 UTC Sunday
    - cron: "41 6 * * 1,2,3,4,5,6" # 6:41 UTC Monday-Saturday
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-image-desktop:
    name: Desktop Images
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      images: '["aurora", "aurora-nvidia", "bluefin", "bluefin-nvidia", "cosmic", "cosmic-nvidia"]'
      image_flavor: Desktop

  build-image-bazzite:
    name: Bazzite Images
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      images: '["bazzite", "bazzite-deck"]'
      image_flavor: Bazzite

  build-image-server:
    name: Server Images
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      images: '["ucore", "ucore-nvidia"]'
      image_flavor: Server

  build-iso-desktop:
    name: Desktop ISOs
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: [build-image-desktop, build-image-server]
    with:
      images: '["aurora", "aurora-nvidia", "bluefin", "bluefin-nvidia", "cosmic", "cosmic-nvidia"]'
      image_flavor: Desktop

  build-iso-bazzite:
    name: Bazzite ISOs
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: build-image-bazzite
    with:
      images: '["bazzite", "bazzite-deck"]'
      image_flavor: Bazzite

  create-release:
    name: Create Release
    needs: [build-iso-desktop, build-iso-bazzite]
    uses: ./.github/workflows/create-release.yml
