---
name: Build m2os
on: # yamllint disable-line rule:truthy rule:comments
  schedule:
    # yamllint disable-line rule:comments
    - cron: "41 6 * * 0" # 6:41 UTC Sunday
    # yamllint disable-line rule:comments
    - cron: "41 6 * * 1,2,3,4,5,6" # 6:41 UTC Monday-Saturday
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:
permissions:
  contents: read
  packages: read

jobs:
  lint:
    name: Lint Project
    uses: ./.github/workflows/lint.yml

  build-image:
    name: Build Images
    needs: [lint]
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        image_flavor: ["Desktop", "Bazzite", "Server"]
    with:
      image_flavor: ${{ matrix.image_flavor }}

  build-iso:
    name: Build ISOs
    if: ${{ ! contains(github.head_ref, 'renovate') }}
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: [build-image]
    strategy:
      fail-fast: false
      matrix:
        image_flavor: ["Desktop", "Bazzite"]
    with:
      image_flavor: ${{ matrix.image_flavor }}

  gen-sbom:
    name: Generate SBOMs
    if: ${{ ! contains(github.head_ref, 'renovate') }}
    needs: [build-image]
    uses: ./.github/workflows/gen-sbom.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        image_flavor: ["Desktop", "Bazzite", "Server"]
    with:
      image_flavor: ${{ matrix.image_flavor }}

  changelogs:
    name: Generate Changelogs
    if: ${{ ! contains(github.head_ref, 'renovate') }}
    uses: ./.github/workflows/changelogs.yml
    secrets: inherit
    needs: ["build-iso"]
    strategy:
      fail-fast: false
      matrix:
        target: ["Desktop", "Bazzite"]
    with:
      target: ${{ matrix.target }}

  create-release:
    name: Create Release
    if: ${{ ! contains(github.head_ref, 'renovate') }}
    needs: ["changelogs", "gen-sbom"]
    uses: ./.github/workflows/create-release.yml
