name: Build m2os
on:
  schedule:
    - cron: "41 6 * * 0" # 6:41 UTC Sunday
    - cron: "41 6 * * 1,2,3,4,5,6" # 6:41 UTC Monday-Saturday
  push:
    branches:
      - main
  merge_group:
  workflow_dispatch:

permissions: 
  contents: read
  packages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  push-desktop-stable:
    uses: ./.github/workflows/build-desktop.yml
    secrets: inherit
    with:
      tag_version: stable

  push-desktop-beta:
    uses: ./.github/workflows/build-desktop.yml
    secrets: inherit
    with:
      tag_version: beta

  push-server:
    uses: ./.github/workflows/build-server.yml
    secrets: inherit
    
  build-iso:
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: push-desktop-stable
    if: (github.event_name == 'schedule' && github.event.schedule != '41 6 * * 1,2,3,4,5,6') || github.event_name == 'workflow_dispatch' 
    with:
      image_version: stable
  
  build-iso-beta:
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: push-desktop-beta
    if: (github.event_name == 'schedule' && github.event.schedule != '41 6 * * 1,2,3,4,5,6') || github.event_name == 'workflow_dispatch' 
    with:
      image_version: beta