name: Build m2os
on:
  schedule:
    - cron: "41 6 * * 2" # 6:41 UTC every Tuesday
  push:
    branches:
      - main
  merge_group:
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: m2os

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  push-ublue:
    uses: ./.github/workflows/build-bluefin-aurora-bazzite.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write

  push-ucore:
    uses: ./.github/workflows/build-ucore.yml
    secrets: inherit
    permissions: 
      contents: read
      packages: write
      id-token: write
  
  push-cosmic:
    uses: ./.github/workflows/build-cosmic.yml
    secrets: inherit
    permissions: 
      contents: read
      packages: write
      id-token: write
    
  build-iso:
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: [push-ublue, push-cosmic]
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
      id-token: write
