name: Build m2os
on:
  schedule:
    - cron: "41 6 * * 0" # 6:41 UTC Sunday
    - cron: "41 6 * * 1,2,3,4,5,6" # 6:41 UTC Monday-Saturday
  merge_group:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-image-desktop:
    name: Desktop Images
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      images: '["aurora", "aurora-nvidia", "bluefin", "bluefin-nvidia", "cosmic", "cosmic-nvidia"]'
      image_flavor: Desktop

  build-image-bazzite:
    name: Bazzite Images
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      images: '["bazzite", "bazzite-deck"]'
      image_flavor: Bazzite

  build-image-server:
    name: Server Images
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      images: '["ucore", "ucore-nvidia"]'
      image_flavor: Server

  changelogs-desktop:
    name: Desktop Changelogs
    uses: ./.github/workflows/changelogs.yml
    secrets: inherit
    needs: build-image-desktop
    with:
      target: stable

  changelogs-bazzite:
    name: Bazzite Changelogs
    uses: ./.github/workflows/changelogs.yml
    secrets: inherit
    needs: build-image-bazzite
    with:
      target: bazzite

  changelogs-server-stable:
    name: Server Changelogs
    uses: ./.github/workflows/changelogs.yml
    secrets: inherit
    needs: build-image-server
    with:
      target: ucore

  build-iso-desktop:
    name: Desktop ISOs
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: build-image-desktop
    if: contains(fromJson('["workflow_dispatch", "workflow_call"]'), github.event_name) || github.event.schedule == '41 6 * * 0'
    with:
      images: '["aurora", "aurora-nvidia", "bluefin", "bluefin-nvidia", "cosmic", "cosmic-nvidia"]'
      image_flavor: Desktop

  build-iso-bazzite:
    name: Bazzite ISOs
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: build-image-bazzite
    if: contains(fromJson('["workflow_dispatch", "workflow_call"]'), github.event_name) || github.event.schedule == '41 6 * * 0'
    with:
      images: '["bazzite", "bazzite-deck"]'
      image_flavor: Bazzite
