---
name: Build m2os
on:
  schedule:
    - cron: "41 6 * * 0"  # 6:41 UTC Sunday
    - cron: "41 6 * * 1,2,3,4,5,6"  # 6:41 UTC Monday-Saturday
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:
permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  build-image:
    name: Build Images
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        image_flavor: ["Desktop", "Bazzite", "Server"]
    with:
      image_flavor: ${{ matrix.image_flavor }}
  build-iso:
    name: Build ISOs
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: [build-image]
    strategy:
      fail-fast: false
      matrix:
        image_flavor: ["Desktop", "Bazzite"]
    with:
      image_flavor: ${{ matrix.image_flavor }}
  create-release:
    name: Create Release
    needs: [build-iso]
    uses: ./.github/workflows/create-release.yml
