name: Build m2os
on:
  schedule:
    - cron: "41 6 * * 0" # 6:41 UTC Sunday
    - cron: "41 6 * * 1,2,3,4,5,6" # 6:41 UTC Monday-Saturday
  push:
    branches:
      - main
  merge_group:
  workflow_dispatch:

permissions: 
  contents: write
  packages: write
  id-token: write

jobs:
  push-desktop-stable:
    uses: ./.github/workflows/build-desktop.yml
    secrets: inherit
    with:
      tag_version: stable

  push-desktop-beta:
    uses: ./.github/workflows/build-desktop.yml
    secrets: inherit
    with:
      tag_version: beta
    
  changelogs-desktop-stable-bluefin:
    uses: ./.github/workflows/changelogs.yml
    secrets: inherit
    needs: push-desktop-stable
    with:
      target: stable

  changelogs-desktop-stable-bazzite:
    uses: ./.github/workflows/changelogs.yml
    secrets: inherit
    needs: push-desktop-stable
    with:
      target: bazzite

  push-server:
    uses: ./.github/workflows/build-server.yml
    secrets: inherit
    
  changelogs-server-stable:
    uses: ./.github/workflows/changelogs.yml
    secrets: inherit
    needs: push-server
    with:
      target: ucore

  build-iso:
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: push-desktop-stable
    if: contains(fromJson('["workflow_dispatch", "workflow_call"]'), github.event_name) || github.event.schedule == '41 6 * * 0'
    with:
      image_version: stable
  
  build-iso-beta:
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: push-desktop-beta
    if: contains(fromJson('["workflow_dispatch", "workflow_call"]'), github.event_name) || github.event.schedule == '41 6 * * 0'
    with:
      image_version: beta