name: Build m2os
on:
  schedule:
    - cron: "41 6 * * 0" # 6:41 UTC Sunday
    - cron: "41 6 * * 1,2,3,4,5,6" # 6:41 UTC Monday-Saturday
  push:
    branches:
      - main
  merge_group:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  push-desktop-bluefin:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      images: '["aurora", "aurora-nvidia", "bluefin", "bluefin-nvidia", "cosmic", "cosmic-nvidia"]'
      image_flavor: Desktop

  push-desktop-bazzite:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      images: '["bazzite", "bazzite-deck"]'
      image_flavor: Bazzite

  changelogs-desktop-bluefin:
    uses: ./.github/workflows/changelogs.yml
    secrets: inherit
    needs: push-desktop-bluefin
    with:
      target: stable

  changelogs-desktop-stable-bazzite:
    uses: ./.github/workflows/changelogs.yml
    secrets: inherit
    needs: push-desktop-bazzite
    with:
      target: bazzite

  push-server:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      images: '["ucore", "ucore-nvidia"]'
      image_flavor: Server

  changelogs-server-stable:
    uses: ./.github/workflows/changelogs.yml
    secrets: inherit
    needs: push-server
    with:
      target: ucore

  build-iso-bluefin:
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: push-desktop-bluefin
    if: contains(fromJson('["workflow_dispatch", "workflow_call"]'), github.event_name) || github.event.schedule == '41 6 * * 0'
    with:
      images: '["aurora", "aurora-nvidia", "bluefin", "bluefin-nvidia", "cosmic", "cosmic-nvidia"]'
      image_flavor: Desktop

  build-iso-bazzite:
    uses: ./.github/workflows/build-iso.yml
    secrets: inherit
    needs: push-desktop-bazzite
    if: contains(fromJson('["workflow_dispatch", "workflow_call"]'), github.event_name) || github.event.schedule == '41 6 * * 0'
    with:
      images: '["bazzite", "bazzite-deck"]'
      image_flavor: Bazzite
