---
name: Generate SBOMs
on: # yamllint disable-line rule:truthy rule:comments
  workflow_call:
    inputs:
      image_flavor:
        type: string
    secrets:
      SIGNING_SECRET:
        required: true
concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref
    || github.run_id }}-${{ inputs.image_flavor }}-sbom
  cancel-in-progress: true
env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}
  SET_X: 1

jobs:
  get-images:
    name: Get Images for SBOMs
    permissions:
      actions: read
    outputs:
      images: ${{ steps.images.outputs.images }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length rule:comments
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Get Images for Build
        id: images
        uses: ./.github/actions/get-images
        with:
          image_flavor: ${{ inputs.image_flavor }}

  sbom-image:
    name: ${{ matrix.image }}
    needs: ["get-images"]
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      packages: write
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        image: ["${{ fromJson(needs.get-images.outputs.images) }}"]
    container:
      # yamllint disable-line rule:line-length rule:comments
      image: "ghcr.io/ublue-os/devcontainer:latest@sha256:c91ff8d18aff262796dc4a351945c3a56fa2e199368911a5067c8e9e0721b4b1"
      # yamllint disable-line rule:line-length rule:comments
      options: "--privileged --volume /:/host-sys --volume /var/lib/containers:/var/lib/containers
        --security-opt seccomp=unconfined --security-opt apparmor=unconfined --security-opt
        label=disable --user 0:0"
    steps:
      - name: Maximize build space
        shell: bash
        run: |
          set -xeuo pipefail
          df -h
          # Remove host toolchains, browsers
          shopt -s nullglob
          printf '/host-sys%s\0' /opt/PyPy \
                                /opt/az \
                                /opt/node/ \
                                /opt/pipx \
                                /opt/go \
                                /opt/Ruby \
                                /usr/lib/llvm-* \
                                /usr/local/julia* \
                                /usr/local/lib/android \
                                /usr/share/dotnet \
                                /usr/share/swift \
                                /usr/local/.ghcup \
                                /usr/lib/firefox \
                                /opt/google/chrome \
                                /opt/microsoft/msedge \
              | xargs -0 -n1 -P4 rm -rf
          df -h

      - name: Checkout
        # yamllint disable-line rule:line-length rule:comments
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Mark Directory as Safe
        run: git config --system --ad safe.directory "$GITHUB_WORKSPACE"

      - name: Download OCI-Archive
        # yamllint disable-line rule:line-length rule:comments
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ env.IMAGE_NAME }}_${{ matrix.image }}.tar
          path: ${{ runner.temp }}

      - name: Load Image into Container Runtime
        shell: bash
        run: |
          set -eou pipefail
          image_registry="${{ env.IMAGE_REGISTRY }}"
          # Load the image into the container runtime (podman)
          cid="$(podman load -i \
            /__w/_temp/${{ env.IMAGE_NAME }}_${{ matrix.image }}.tar | sed 's/Loaded image: //')"
          podman tag "${cid}" \
            ${image_registry,,}/${{ env.IMAGE_NAME }}:${{ matrix.image }}
          podman tag "${cid}" \
          "localhost/${{ env.IMAGE_NAME }}:${{ matrix.image }}"

      - name: Create Rootfs
        shell: bash
        run: |
          set -eou pipefail
          mkdir -p "/__w/_temp/${{ matrix.image }}-rootfs"
          podman container create \
            --replace --name sbom-gen \
            "localhost/${{ env.IMAGE_NAME }}:${{ matrix.image }}"
          podman export sbom-gen | tar -C "/__w/_temp/${{ matrix.image }}-rootfs" -xf -
          podman rm sbom-gen

      - name: Generate SBOM
        id: gen
        run: |
          export SYFT_PARALLISM="$(($(nproc) * 2))"
          export SYFT_SOURCE_NAME="${{ env.IMAGE_NAME }}-${{ matrix.image }}"
          just gen-sbom \
            "/__w/_temp/${{ matrix.image }}-rootfs" \
            "/__w/_temp/${{ matrix.image }}.sbom.json"
          rm -rf "/__w/_temp/${{ matrix.image }}-rootfs"

      - name: Scan SBOM
        # yamllint disable-line rule:line-length rule:comments
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7
        id: scan
        with:
          sbom: /__w/_temp/${{ matrix.image }}.sbom.json
          fail-build: false

      - name: Inspect Sarif
        run: cat ${{ steps.scan.outputs.sarif }}

      - name: Upload Sarif Report
        # yamllint disable-line rule:line-length rule:comments
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc # v4
        if: >-
          contains(fromJson('["workflow_dispatch", "merge_group"]'),
          github.event_name) || github.event.schedule == '41 6 * * 0'
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
          category: ${{ matrix.image }}

      - name: Sign SBOM
        id: sign
        if: >-
          contains(fromJson('["workflow_dispatch", "merge_group"]'),
          github.event_name) || github.event.schedule == '41 6 * * 0'
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          OCI_ARCHIVE: ${{ env.IMAGE_NAME }}_${{ matrix.image }}.tar
        shell: bash
        run: |
          set -eou pipefail

          just sbom-sign \
            "oci-archive:/__w/_temp/${{ env.OCI_ARCHIVE }}" \
            "/__w/_temp/${{ matrix.image }}.sbom.json"

      - name: Upload SBOM
        # yamllint disable-line rule:line-length rule:comments
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: ${{ matrix.image }}.sbom
          path: |-
            /__w/_temp/${{ matrix.image }}.sbom.json*

      - name: Attach SBOM
        id: attest
        if: >-
          contains(fromJson('["workflow_dispatch", "merge_group"]'),
          github.event_name) || github.event.schedule == '41 6 * * 0'
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          OCI_ARCHIVE: ${{ env.IMAGE_NAME }}_${{ matrix.image }}.tar
        shell: bash
        run: |
          set -eou pipefail

          just login-to-ghcr ${{ github.actor }} ${{ github.token }}

          just sbom-attach \
            "oci-archive:/__w/_temp/${{ env.OCI_ARCHIVE }}" \
            "/__w/_temp/${{ matrix.image }}.sbom.json"

  check:
    name: Check Gen SBOM Successful
    permissions:
      actions: read
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    needs: [sbom-image]
    steps:
      - name: Exit on failure
        if: >-
          ${{ contains(fromJson('["failure", "skipped"]'),
          needs.sbom-image.result) }}
        shell: bash
        run: exit 1
      - name: Exit
        shell: bash
        run: exit 0
