---
name: Lint Project
on: # yamllint disable-line rule:truthy rule:comments
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      # yamllint disable-line rule:line-length rule:comments
      image: "ghcr.io/ublue-os/devcontainer:latest@sha256:74af83ac3b3fa573bee61d6d2d5ea5ba59f92f44afc3833d57b05ace66eb98ca"
    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length rule:comments
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        
      - name: Mark Directory as Safe
        run: git config --system --ad safe.directory "$GITHUB_WORKSPACE"
        
      - name: Lint Project
        id: lint
        shell: bash
        run: |-
          just lint
